#
# Standard Makefile for a Webots controller
#
# Author: Olivier.Michel@cyberbotics.com
# Date:   August 29th, 2006.
#

ifndef WEBOTS_HOME_PATH
WEBOTS_HOME_PATH=$(WEBOTS_HOME)
endif

include $(WEBOTS_HOME_PATH)/projects/default/controllers/Makefile.include
